### ISSUE TITLE
refactor: Improve color of hover tertiary

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#105]
**Is your feature request related to a problem? Please describe.**

- `hover tertiary` color has been improved. The color need to be updated in the lib.

**Describe the solution you'd like**

- Change the value of the `hover tertiary` color

**Additional context**

- [Button component figma](https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=1388%3A2858)
- [Jira issue](https://decathlon.atlassian.net/jira/software/projects/DSRUN/boards/2922?selectedIssue=DSRUN-65)

**Comment by GerardPaligot** [comment]
We don't use semantic hover colors.
