### ISSUE TITLE
refactor: TopBar have a wrong start padding when there is a navigation icon 

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#106]
**Is your feature request related to a problem? Please describe.**

- The start padding between the left border of the screen and the title should be 72px/dp but for now, it is 56px/dp.

**Describe the solution you'd like**

**Additional context**

- [Figma](https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=35%3A3850)
- [Jira issue](https://decathlon.atlassian.net/jira/software/projects/DSRUN/boards/2922?selectedIssue=DSRUN-118)

**Comment by GerardPaligot** [comment]
It was an issue on the design specification, not in the technical implementation.

**Comment by GaspardMathon** [comment]
Thanks Gérard
