### ISSUE TITLE
feat: Add all flags for all countries

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#107]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- New flag assets are available and need to be ut in the library

**Additional context**

- [Figma assets](https://www.figma.com/file/Fi9WjIkuax79ujCAjvyoHj/Vitamin---Assets-(v0)?node-id=503%3A4)

**Comment by GerardPaligot** [comment]
What is the diff between current flags and new ones?

**Comment by GaspardMathon** [comment]
You have currently about 30 flags on the android library. There are 216 flags available now.
