### ISSUE TITLE
refactor: 3 small changes in semantic colors

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-android#117]
There are some changes in semantic colors for 3 colors: 

`backgroundPrimary` => from `grey800` to `grey900`
`backgroundSecondary` => from `grey900` to `black`
`backgroundTertiary`=>  from `black` to `grey800`

To help you, here is the PR on vitamin-web: https://github.com/Decathlon/vitamin-web/pull/1127

Thanks for your understanding.

**Comment by GerardPaligot** [comment]
I can see a base color change too with grey400: `#8c96a2` to `#8996a2`. Can you tell us if there are another changes about colors please?

Thanks
