### ISSUE TITLE
refactor: edit card gradient on full-image variant 

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#126]
**Is your feature request related to a problem? Please describe.**

- On card with gradient, contrast is not enough on text (2.83).

**Describe the solution you'd like**

- Let’s improve it → Gradient has to be full height

**Additional context**

- [Figma](https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=1187%3A2858)

**Comment by GerardPaligot** [comment]
Card isn't yet developed.
