### ISSUE TITLE
feat: new icons

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#127]
**Is your feature request related to a problem? Please describe.**

New icons to add : 

- zoom-in-line
- zoom-in-fill
- zoom-out-line
- zoom-out-fill
- tiktok-line
- tiktok-fill

**Describe the solution you'd like**

**Additional context**

[figma](https://www.figma.com/file/ujn50nNMfGKzZJccATv7Vk/Vitamin---Vitamix-icons-(v0)?node-id=335%3A24)

**Comment by charlottemougenot** [comment]
Added in #134
