### ISSUE TITLE
refactor: edit quantity borders

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#128]
**Is your feature request related to a problem? Please describe.**

The quantity component has a different border than the text input

**Describe the solution you'd like**

We need to fix the borders to have the same design

**Additional context**

[FIGMA](https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=4415%3A9576)

**Comment by GerardPaligot** [comment]
The quantity selection isn't yet developed. I think we can close this issue.
