### ISSUE TITLE
refactor: remove 2 rating variants

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#131]
**Is your feature request related to a problem? Please describe.**

- See on Figma the two variants to delete

**Describe the solution you'd like**

**Additional context**

- [FIGMA](https://www.figma.com/file/cmZCNVet64UlDNnDDd4hDV/Vitamin---iOS-14-UI-kit-(v0)?node-id=2862%3A10053)

**Comment by GerardPaligot** [comment]
We are already good.
