### ISSUE TITLE
feat: Add missing flags for "DOM-TOM" countries

### ISSUE THREAD

**Issue by ClementPetitcunot** [Decathlon/vitamin-android#135]
**Is your feature request related to a problem? Please describe.**

We are going to use the Vitamin flags in the CubeInStore application and there are 5 flags missing.

**Describe the solution you'd like**

Below are the 5 flags to add with their associated ISO code. 

**Martinique** -> Code ISO : **MQ** 
![flag_MQ](https://user-images.githubusercontent.com/96111115/181284758-dc20a839-0c1d-4eff-8941-17831902aecb.png)

**Reunion** -> Code ISO : **RE** 
![flag_RE](https://user-images.githubusercontent.com/96111115/181284761-099f7d19-85f4-459a-822e-71fa93086552.png)

**Guadeloupe** -> Code ISO : **GP** 
![flag_GP](https://user-images.githubusercontent.com/96111115/181284763-edc413ec-5bfe-483c-809f-e11b2582be05.png)

**Guyane française** -> Code ISO : **GF**
![flag_GF](https://user-images.githubusercontent.com/96111115/181284765-ab3d166a-d068-4bf7-8ab4-c900ba382e9b.png)

**Nouvelle-Calédonie** -> Code ISO : **NC** 
![flag_NC](https://user-images.githubusercontent.com/96111115/181284767-b565639e-83e2-4ce8-937a-46e6471bb404.png)

**Additional context**

**Comment by Sabrinavigil** [comment]
Hi ! Merged with this issue: https://github.com/Decathlon/vitamin-design/issues/35
