### ISSUE TITLE
bug: can't use Vitamin in XML previews with Dolphin

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/vitamin-android#141]
**Describe the bug**

When we declare a Text with a Vitamin text style, the XML preview is broken

**Steps to reproduce**
1. Create a new Android project
2. Open it with Android Studio Dolphin
3. Create a XML layout file with a Text
4. See the error in the preview window

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textAppearance="?attr/vtmnTextAppearanceBodyRegularText3"
        android:text="Test"
        />

</LinearLayout>
```

> File /Users/GERARD/.gradle/caches/transforms-3/06b5c1790b23bad5cd0964c1d1c347df/transformed/foundation-0.4.0-beta01/res/font/roboto_family.xml does not exist (or is not a file)

**Expected behavior**

Preview not broken and can render my layout file with Vitamin components.
Note that they aren't any bug with Android Studio Chimpmunk.

**Screenshots**

<img width="1254" alt="Capture of Android Studio Dolphin to show the bug in action" src="https://user-images.githubusercontent.com/1913901/191439457-274379c6-abb5-445e-80d9-0f7570ca1e35.png">

**Device (please complete the following information):**
- Version Android Studio Dolphin

**Comment by Smoochibi** [comment]
The issue can also be reproduced with `Android Studio Electric Eel | 2022.1.1 Canary 10`.

**Comment by JocelynDavid** [comment]
Hello, I got this issue as well with :

Android Studio Dolphin | 2021.3.1
Build #AI-213.7172.25.2113.9014738, built on August 31, 2022

Different types of errors : 

File /Users/JOCELYN/.gradle/caches/transforms-3/cad4f26f5dc89c291f258fa5f76e2495/transformed/foundation-0.4.0-beta01/res/font/roboto_family.xml does not exist (or is not a file)

I tried clean cache, delete /Users/JOCELYN gradle folder, invalidate cache. Nothing worked .

Any idea what is causing this issue?

**Comment by JocelynDavid** [comment]
Hello, any news on this?

**Comment by GerardPaligot** [comment]
@JocelynDavid Can you test again on Android Studio Dolphin? It works for me without any changes in Vitamin Android and with Android Studio Dolphin 2021.3.1 Patch 1.

**Comment by JocelynDavid** [comment]
<img width="1220" alt="Capture d’écran 2022-11-30 à 15 22 03" src="https://user-images.githubusercontent.com/51441110/204820388-0ce67ecc-7b25-4b4a-9218-480e0fa71a6a.png">
No changes for me ?

**Comment by mdupierreux** [comment]
According to this issue https://issuetracker.google.com/issues/248473636 it's an Android Studio bug that has been fixed in Beta & Canary releases (or not : https://issuetracker.google.com/issues/248473636#comment23 )

**Comment by ManonPolle** [comment]
I closed it as it is fixed in last Android Studio version. 
Please re open an issue if a problem still persists
