### ISSUE TITLE
bug: Text input counter on Android

### ISSUE THREAD

**Issue by marcBeyseckerFrog** [Decathlon/vitamin-android#183]
For the TextInput composable, 
if the parameter "Helper text" is null, the counter is on the left side instead of the right side.

**Comment by ManonPolle** [comment]
Thanks @marcBeyseckerFrog for reporting this issue ! 
We'll do our best to look at it shortly. 
& If you want, feel free to contribute

**Comment by apauchet** [comment]
Hello @marcBeyseckerFrog. 
I analyzed your issue, but sorry, I can not reproduce it. 
If your problem persists please give me more information and screen view. 
Thanks

**Comment by apauchet** [comment]
This issue is about vitamin-compose project and it has solved with this fix
https://github.com/Decathlon/vitamin-compose/pull/165
