### ISSUE TITLE
Update buttons to be compliant with v0.10

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/vitamin-android#22]
**Describe the solution you'd like**

Design specification of secondary button has been modified: https://www.decathlon.design/726f8c765/p/8008f8-button/b/50afe1/t/62030b

New button type has been created: https://www.decathlon.design/726f8c765/p/8008f8-button/b/50afe1/t/043598

**Comment by MaximeJineMaraval** [comment]
I've also noticed some differences with the library : 

- The secondary reversed has disappeared.
- The primary reverse has changed too. 

### So complete list changes should be : 

- [Primary reverse changes](https://www.decathlon.design/726f8c765/p/8008f8-button/b/50afe1/t/54428f)
- [Secondary changes](https://www.decathlon.design/726f8c765/p/8008f8-button/b/50afe1/t/62030b)
- Secondary reverse deletion
- [Tiertary addition](https://www.decathlon.design/726f8c765/p/8008f8-button/b/50afe1/t/043598)

**Comment by MaximeJineMaraval** [comment]
There is some difference today between decathlon.design and Figma due to the transparent color used for the ripple effect. This will be fixed with the new core colors. I switch this issue to WIP, waiting for the fix.
