### ISSUE TITLE
Use 38% of opacity on each disabled state

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-android#52]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

This issue is there just to ensure that we have 38% of opacity on each disabled state.
Feel free if you have question.

**Comment by GerardPaligot** [comment]
It is already the case. A `dimen` (`vtmn_states_disabled`) is created in `foundation` module which is used in all components.
