### ISSUE TITLE
Add new icons (car, walk, train & mic)

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-android#53]
There are new icons (car, walk, train and mic) in line and fill modes.

Link to icons: https://www.figma.com/file/ujn50nNMfGKzZJccATv7Vk/?node-id=335%3A24

**Comment by GerardPaligot** [comment]
Missing icon list:
* feedback (line/fill)
* phone (line/fill)
* attachment (line only)
* link (line only)
* unlink (line only)
* list check (line only)
* exchange (line/fill) - wrong icon
* return (line/fill)
* heart pulse (line/fill)
* Telegram (line/fill)
* viber (line/fill)
* truck (line/fill)
* earth (line/fill)
* navigation (line/fill)
* distance (line/fill)
* train (line/fill)
* car (line/fill)
* walk (line/fill)
* mic (line/fill)
* selected by decathlon (line only)
* history (line/fill)
* package (line/fill) - wrong icon
* upload (line/fill)
* share
* refresh (line/fill)
* counter (line/fill)
* group (line/fill)
* all icons in weather section (line/fill)
* all flags

**Comment by lauthieb** [comment]
Payment section and flags are Vitamin assets (yes they already are in icons also but they will only be in Vitamin assets later), do you think it is possible to separate them from the icons package with a specific assets package?

**Comment by GerardPaligot** [comment]
Ok, we'll create a module `foundation-icons` and another one `foundation-assets` but technically, it will be the same for developers.
