### ISSUE TITLE
Changes in colors and new semantic colors

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-android#55]
There are few changes in colors of components and new semantic colors, here is the summary:
* The color of helper text and letters counter for inputs is changed to Content Secondary (instead of tertiary)
* The color of the number of reviews on ratings is changed to Content Secondary (instead of tertiary)
* Core light: ContentSecondary has been renamed in ContentTertiary
* Core light: The new ContentSecondary is now based on grey600
* Core dark: ContentSecondary has been renamed in ContentTertiary
* Core dark: The new ContentSecondary is now based on grey200

**Comment by GerardPaligot** [comment]
We need to create `vtmnBorderTertiary` too for dark and light theme.
