### ISSUE TITLE
Can't change the buttons theme color in Framelayout

### ISSUE THREAD

**Issue by liguopengbenli** [Decathlon/vitamin-android#63]
Can't override button's background color in many situations

**Describe the bug**
sometimes app design needs more custom background color for button, when apply the theme globally it seems impossible to override button background color in xml  

**To Reproduce**

    1. apply the theme globally (the parent of app theme)
    2. can't override some buttons' background color in xml 

**Smartphone (please complete the following information):**

 - Device: [Nexus 4]
 - OS: [android R]
 - Version [API 30 ]

**Comment by GerardPaligot** [comment]
Thanks for your report @liguopengbenli 

I know there is a current rework of the Button implementation in progress by @MaximeJineMaraval about #22 and #54 but can you provide more information about "some buttons' background color in xml"? Which one?

And can you tell me why do you need to change the background? I don't know any case where it is pertinent to override the background of a button when you build a Decathlon app.

Thanks in advance!

**Comment by liguopengbenli** [comment]
@GerardPaligot in the case, yes the module cover most of case, exception is appeared in:
When the button is in a card view, the button background becomes the color of card view 
I guess when the button in frame layout it presents the same problem

**Comment by liguopengbenli** [comment]
I ask a friend, he said there may be some theme which isn't available yet in release version, so I think my issue will be resolved. when the new theme come with new release version.

**Comment by liguopengbenli** [comment]
I think I resolve my issue, android x compact button doesn't work but materiel button is working

**Comment by GerardPaligot** [comment]
Yes, we try to give a default implementation for the "legacy" views but if you are using `Material{View}` or the `Vitamin{View}` classes (this last one is our recommendation), you shouldn't have any issue (or it is a bug).

Happy to see that everything work now!
