### ISSUE TITLE
Toast component

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-android#66]
**Decathlon.design link**

https://www.decathlon.design/726f8c765/p/4450b2-toast/b/81bb90

**Material.io link**

https://material.io/archive/guidelines/components/snackbars-toasts.html

**Comment by charlottemougenot** [comment]
As discussed with the team, as Android deprecated the setView and with it custom toast views, we won't create a custom toast component. 

On [Toast | Android Developers](https://developer.android.com/reference/android/widget/Toast) :

`setView(View view)
This method was deprecated in API level 30. Custom toast views are deprecated. Apps can create a standard text toast with the makeText(android.content.Context, java.lang.CharSequence, int) method, or use a Snackbar when in the foreground. Starting from Android Build.VERSION_CODES#R, apps targeting API level Build.VERSION_CODES#R or higher that are in the background will not have custom toast views displayed.`
