### ISSUE TITLE
Deploy artifact to maven central

### ISSUE THREAD

**Issue by MaximeJineMaraval** [Decathlon/vitamin-android#7]
**Is your feature request related to a problem? Please describe.**

There isn't any artifact published on an artifact registry to use the library by mobile android projects.

**Describe the solution you'd like**

At each push on main branch, we must push artifacts to Maven Central with Decathlon credentials.

**Additional context**

This issue need to be worked with Gregoire Weymel.

**Comment by GerardPaligot** [comment]
0.1.0-beta01 published from Bitrise to Maven Central!
