### ISSUE TITLE
feat: add radius tokens (+ semantic aliases)

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#80]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

New design tokens for border radius have been released on figma : https://www.figma.com/file/zDZIyayUlr1yTWrsi7cFoo/Vitamin---Web-UI-kit-(v0)?node-id=8060%3A18264

-> We need to create radius token in dev for the web components

**Comment by GerardPaligot** [comment]
I didn't see any usage of these radius tokens inside components. It is an omission?

@GaspardMathon Because this repository is public, give only official and public links here. If borders aren't documented on the official design system website, you shouldn't create an issue here.
