### ISSUE TITLE
feat: add icon alone variant button

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#85]
**Is your feature request related to a problem? Please describe.**

- We need to add an icon alone variant on android buttons.

**Additional context**

- Quantity in figma : https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=2709%3A5110
- Button in Figma : https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=519%3A4206

**Comment by GerardPaligot** [comment]
Component abandoned!
