### ISSUE TITLE
refactor: change conversion button content color

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- For the `conversion` variant button, we need to change the contentPrimary color to contentAccent color 

**Additional context**

- Figma : https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=1388%3A2858

**Comment by GerardPaligot** [comment]
Already contentAccent color used by conversion variant button
