### ISSUE TITLE
feat: add list component

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#92]
**New component**

- Add `list` component

**Documentation links**

- [Documentation](https://www.decathlon.design/726f8c765/v/0/p/078570-list-beta)
- [Figma](https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=2692%3A5198)
- [Material](https://material.io/components/lists)

**Comment by ManonPolle** [comment]
We won't develop a template for list components for now
