### ISSUE TITLE
feat: add divider component

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#94]
**New component**

- Add `divider` component

**Documentation links**

- [Documentation](https://www.decathlon.design/726f8c765/v/0/p/28ad9b-divider-beta)
- [Figma](https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=2599%3A4745)

**Comment by MaximeJineMaraval** [comment]
- [ ] Divider module
- [ ] Sample screen
- [ ] Inset
- [ ] FullBleed
- [ ] Middle
- [ ] Native divider?
- [ ] Divider README
- [ ] Vitamin README
