### ISSUE TITLE
feat: add search component

### ISSUE THREAD

**Issue by GaspardMathon** [Decathlon/vitamin-android#96]
**New component**

- Add `search` component

**Documentation links**

- [Documentation](https://www.decathlon.design/726f8c765/v/0/p/666649-search-beta)
- [Figma](https://www.figma.com/file/WkGTfR63Nf2AGHSoRvEhWC/Vitamin---Android-UI-kit-(v0)?node-id=2154%3A5897)

**Comment by MohitMandalia** [comment]
Can I help contributing to something here, if it is open for contribution do let me know.

Thanks

**Comment by GerardPaligot** [comment]
Already developed.
